# Generated by Django 5.2.6 on 2025-10-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Región')),
                ('numero_region', models.IntegerField(unique=True, verbose_name='Número de Región')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Región Sanitaria',
                'verbose_name_plural': 'Regiones Sanitarias',
                'ordering': ['numero_region'],
            },
        ),
        migrations.CreateModel(
            name='CentroAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Establecimiento')),
                ('codigo', models.CharField(help_text='Código único del establecimiento', max_length=20, unique=True, verbose_name='Código')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('es_regional', models.BooleanField(default=False, help_text='Indica si este centro tiene responsabilidad regional', verbose_name='¿Es Centro Regional?')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_atencion', to='examen.region', verbose_name='Región Sanitaria')),
            ],
            options={
                'verbose_name': 'Centro de Atención',
                'verbose_name_plural': 'Centros de Atención',
                'ordering': ['region', 'nombre'],
            },
        ),
    ]
