# Generated by Django 5.2.6 on 2025-10-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('nivel', models.CharField(choices=[('LNP', 'Laboratorio Nacional de Parasitología'), ('REG', 'Regional'), ('CAT', 'Centro de Atención')], max_length=3, verbose_name='Nivel de Acceso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('puede_crear_usuarios', models.BooleanField(default=False, verbose_name='¿Puede crear usuarios?')),
                ('puede_ver_todas_regiones', models.BooleanField(default=False, verbose_name='¿Puede ver todas las regiones?')),
                ('puede_generar_reportes_nacionales', models.BooleanField(default=False, verbose_name='¿Puede generar reportes nacionales?')),
                ('puede_editar_configuracion', models.BooleanField(default=False, verbose_name='¿Puede editar configuración del sistema?')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('centro_atencion', models.ForeignKey(blank=True, help_text='Solo para usuarios CAT (Centro de Atención)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='examen.centroatencion', verbose_name='Centro de Atención Asignado')),
                ('region', models.ForeignKey(blank=True, help_text='Solo para usuarios REG (Regional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='examen.region', verbose_name='Región Asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='examen.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
    ]
