# Generated by Django 5.2.6 on 2025-10-13 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_rol_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='Formato: 0801-1990-12345', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener el formato: 0801-1990-12345', regex='^\\d{4}-\\d{4}-\\d{5}$')], verbose_name='DNI')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo Apellido')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Fecha de Nacimiento')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('direccion', models.TextField(verbose_name='Dirección Completa')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('centro_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='examen.centroatencion', verbose_name='Establecimiento de Salud')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Creó el Expediente')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['dni'], name='examen_expe_dni_a9983b_idx'), models.Index(fields=['centro_atencion', '-fecha_creacion'], name='examen_expe_centro__0b77f9_idx')],
            },
        ),
    ]
