# Generated by Django 5.2.6 on 2025-10-13 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_examen', models.CharField(help_text='Código único del examen', max_length=20, unique=True, verbose_name='Número de Examen')),
                ('fecha_examen', models.DateField(verbose_name='Fecha del Examen')),
                ('responsable_analisis', models.CharField(blank=True, max_length=200, verbose_name='Responsable del Análisis')),
                ('consistencia', models.CharField(choices=[('FOR', 'Formada'), ('BLA', 'Blanda'), ('LIQ', 'Líquida/Diarreica')], max_length=3, verbose_name='Consistencia de la Muestra')),
                ('moco', models.CharField(choices=[('N', 'No se observa'), ('E', 'Escaso'), ('M', 'Moderado'), ('A', 'Abundante')], default='N', max_length=1, verbose_name='Moco')),
                ('sangre_macroscopica', models.CharField(choices=[('NO', 'No'), ('SI', 'Sí')], default='NO', max_length=2, verbose_name='Sangre Macroscópica')),
                ('resultado', models.CharField(choices=[('NEG', 'Negativo'), ('POS', 'Positivo')], default='NEG', editable=False, max_length=3, verbose_name='Resultado')),
                ('entamoeba_histolytica', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Entamoeba histolytica')),
                ('entamoeba_coli', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Entamoeba coli')),
                ('entamoeba_hartmanni', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Entamoeba hartmanni')),
                ('endolimax_nana', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Endolimax nana')),
                ('iodamoeba_butschlii', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Iodamoeba bütschlii')),
                ('giardia_intestinalis', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Giardia intestinalis')),
                ('pentatrichomonas_hominis', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Pentatrichomonas hominis')),
                ('chilomastix_mesnili', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Chilomastix mesnili')),
                ('balantidium_coli', models.CharField(blank=True, choices=[('', 'No se observa'), ('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste')], max_length=2, verbose_name='Balantidium coli')),
                ('blastocystis_sp', models.CharField(blank=True, choices=[('', 'No se observa'), ('O', 'Ooquiste')], max_length=1, verbose_name='Blastocystis sp')),
                ('cystoisospora_belli', models.CharField(blank=True, choices=[('', 'No se observa'), ('O', 'Ooquiste')], max_length=1, verbose_name='Cystoisospora belli')),
                ('cyclospora_cayetanensis', models.CharField(blank=True, choices=[('', 'No se observa'), ('O', 'Ooquiste')], max_length=1, verbose_name='Cyclospora cayetanensis')),
                ('cryptosporidium_spp', models.CharField(blank=True, choices=[('', 'No se observa'), ('O', 'Ooquiste')], max_length=1, verbose_name='Cryptosporidium spp')),
                ('ascaris_lumbricoides', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Ascaris lumbricoides')),
                ('ascaris_intensidad', models.CharField(blank=True, choices=[('', 'No aplica'), ('L', 'Leve'), ('M', 'Moderada'), ('S', 'Severa')], help_text='Solo aplica para A. lumbricoides', max_length=1, verbose_name='Intensidad de Infección (Kato-Katz)')),
                ('trichuris_trichiura', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Trichuris trichiura')),
                ('necator_americanus', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Necator americanus')),
                ('strongyloides_stercoralis', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Strongyloides stercoralis')),
                ('enterobius_vermicularis', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Enterobius vermicularis')),
                ('taenia_spp', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('P', 'Proglótidos'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Taenia spp')),
                ('hymenolepis_diminuta', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Hymenolepis diminuta')),
                ('rodentolepis_nana', models.CharField(blank=True, choices=[('', 'No se observa'), ('H', 'Huevos'), ('L', 'Larva'), ('G', 'Gusano Adulto')], max_length=1, verbose_name='Rodentolepis nana')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('centro_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='examen.centroatencion', verbose_name='Establecimiento de Salud')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='examen.expediente', verbose_name='Expediente del Paciente')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Creó la Muestra')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['-fecha_examen'],
                'indexes': [models.Index(fields=['numero_examen'], name='examen_mues_numero__d3feb6_idx'), models.Index(fields=['expediente', '-fecha_examen'], name='examen_mues_expedie_5e5cbc_idx'), models.Index(fields=['centro_atencion', '-fecha_examen'], name='examen_mues_centro__59275e_idx'), models.Index(fields=['resultado', '-fecha_examen'], name='examen_mues_resulta_233d35_idx')],
            },
        ),
    ]
