# Generated by Django 5.2.6 on 2025-10-20 18:17

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='año_epidemiologico',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Año Epidemiológico'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='semana_numero',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Número de Semana'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='centro_atencion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', help_text='Solo para usuarios CAT (Centro de Atención)', null=True, on_delete=django.db.models.deletion.CASCADE, to='examen.centroatencion', verbose_name='Centro de Atención Asignado'),
        ),
        migrations.CreateModel(
            name='SemanaEpidemiologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('semana', models.IntegerField(help_text='Semana según ISO 8601', verbose_name='Número de Semana (1-53)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio (Lunes)')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin (Domingo)')),
                ('total_muestras', models.IntegerField(default=0, verbose_name='Total de Muestras')),
                ('total_positivas', models.IntegerField(default=0, verbose_name='Total Positivas')),
                ('total_negativas', models.IntegerField(default=0, verbose_name='Total Negativas')),
                ('alerta_activa', models.BooleanField(default=False, verbose_name='¿Alerta Epidemiológica Activa?')),
                ('notas', models.TextField(blank=True, verbose_name='Notas o Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semana Epidemiológica',
                'verbose_name_plural': 'Semanas Epidemiológicas',
                'ordering': ['-año', '-semana'],
                'indexes': [models.Index(fields=['año', 'semana'], name='examen_sema_año_2a17d9_idx'), models.Index(fields=['-año', '-semana'], name='examen_sema_año_97bd7e_idx')],
                'unique_together': {('año', 'semana')},
            },
        ),
        migrations.AddField(
            model_name='muestra',
            name='semana_epidemiologica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='examen.semanaepidemiologica', verbose_name='Semana Epidemiológica'),
        ),
    ]
