# Generated by Django 5.2.6 on 2025-10-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0005_muestra_año_epidemiologico_muestra_semana_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento')),
                ('codigo', models.CharField(help_text='Código de 2 dígitos (01-18)', max_length=2, unique=True, verbose_name='Código Administrativo')),
                ('extension_territorial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Extensión Territorial (km²)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('codigo', models.CharField(help_text='Código de 4 dígitos (XXYY)', max_length=4, unique=True, verbose_name='Código Administrativo')),
                ('es_cabecera', models.BooleanField(default=False, help_text='Marca si este municipio es la cabecera del departamento', verbose_name='¿Es Cabecera Departamental?')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='examen.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['departamento', 'codigo'],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
    ]
