# Generated by Django 5.2.6 on 2025-10-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_departamento_municipio'),
    ]

    operations = [
    ]
