# Generated by Django 5.1.4 on 2025-01-13 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Centro')),
                ('direccion', models.TextField(verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Región')),
                ('numero_region', models.IntegerField(unique=True, verbose_name='Número de Región')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('Edad', models.IntegerField()),
                ('consistencia', models.CharField(choices=[('F', 'Formada'), ('B', 'Blanda'), ('D', 'Diarreica')], max_length=2, verbose_name='Consistencia')),
                ('moco', models.CharField(choices=[('E', 'Escaso'), ('M', 'Moderado'), ('A', 'Abundante'), ('N', 'No se observa')], max_length=2, verbose_name='Moco')),
                ('sangre_macroscopica', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente')], max_length=2, verbose_name='Sangre Macroscópica')),
                ('Entamoeba_histolytica', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Entamoeba histolytica')),
                ('Entamoeba_coli', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Entamoeba coli')),
                ('Entamoeba_hartmanni', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Entamoeba hartmanni')),
                ('Endolimax_nana', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Endolimax nana')),
                ('Iodamoeba_bütschlii', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Iodamoeba bütschlii')),
                ('Blastocystis_sp', models.CharField(choices=[('O', 'Ooquiste'), ('N', 'No se observa')], max_length=2, verbose_name='Blastocystis sp')),
                ('Giardia_intestinalis', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Giardia intestinalis')),
                ('Pentatrichomonas_hominis', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Pentatrichomonas hominis')),
                ('Chilomastix_mesnili', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Chilomastix mesnili')),
                ('Balantidium_coli', models.CharField(choices=[('T', 'Trophozoito'), ('Q', 'Quiste'), ('TQ', 'Trophozoito y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Balantidium coli')),
                ('Cystoisospora_belli', models.CharField(choices=[('O', 'Ooquiste'), ('N', 'No se observa')], max_length=2, verbose_name='Cystoisospora belli')),
                ('Cyclospora_cayetanensis', models.CharField(choices=[('O', 'Ooquiste'), ('N', 'No se observa')], max_length=2, verbose_name='Cyclospora cayetanensis')),
                ('Criptosporidium_spp', models.CharField(choices=[('O', 'Ooquiste'), ('N', 'No se observa')], max_length=2, verbose_name='Criptosporidium spp')),
                ('Strongyloides_stercoralis', models.CharField(choices=[('L', 'Larva'), ('N', 'No se observa')], max_length=2, verbose_name='Strongyloides stercoralis')),
                ('Ascaris_lumbricoides', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('N', 'No se observa')], max_length=2, verbose_name='Ascaris lumbricoides')),
                ('Trichuris_trichiura', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('N', 'No se observa')], max_length=2, verbose_name='Trichuris trichiura')),
                ('Necator_americanus', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('N', 'No se observa')], max_length=2, verbose_name='Necator americanus')),
                ('Enterobius_vermicularis', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('N', 'No se observa')], max_length=2, verbose_name='Enterobius vermicularis')),
                ('Taenia_spp', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('P', 'Proglotidos'), ('N', 'No se observa')], max_length=2, verbose_name='Taenia spp')),
                ('Hymenolepis_diminuta', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('N', 'No se observa')], max_length=2, verbose_name='Hymenolepis diminuta')),
                ('Rodentolepis_nana', models.CharField(choices=[('H', 'Huevos'), ('G', 'Gusano Adulto'), ('N', 'No se observa')], max_length=2, verbose_name='Rodentolepis nana')),
                ('Intensidad_de_la_Infección', models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('S', 'Severa')], max_length=2, verbose_name='Intensidad de la Infección')),
                ('No_se_observaron_parásitos', models.BooleanField()),
                ('Expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='core.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_atencion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centroatencion', verbose_name='Centro de Atención')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='centroatencion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_atencion', to='core.region', verbose_name='Región'),
        ),
    ]
