# Generated by Django 5.1.4 on 2025-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='Intensidad_de_la_Infección',
        ),
        migrations.AddField(
            model_name='muestra',
            name='Intensidad_de_la_Infección_KATO_KATZ',
            field=models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('S', 'Severa')], default='L', max_length=2, verbose_name='Intensidad de la Infección KATO-KATZ'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Balantidium_coli',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Balantidium coli'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Chilomastix_mesnili',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Chilomastix mesnili'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Endolimax_nana',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Endolimax nana'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Entamoeba_coli',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Entamoeba coli'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Entamoeba_hartmanni',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Entamoeba hartmanni'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Entamoeba_histolytica',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Entamoeba histolytica'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Giardia_intestinalis',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Giardia intestinalis'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Iodamoeba_bütschlii',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Iodamoeba bütschlii'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='Pentatrichomonas_hominis',
            field=models.CharField(choices=[('T', 'Trofozoíto'), ('Q', 'Quiste'), ('TQ', 'Trofozoíto y Quiste'), ('N', 'No se observa')], max_length=2, verbose_name='Pentatrichomonas hominis'),
        ),
    ]
