# Generated by Django 5.1.4 on 2025-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_muestra_intensidad_de_la_infección_kato_katz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='DNI'),
        ),
    ]
