# Generated by Django 5.1.4 on 2025-02-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_expediente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='CentroAtencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='muestras', to='core.centroatencion'),
        ),
    ]
